# Generated by Django 3.2.13 on 2022-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220831_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='update_at',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
